### ISSUE TITLE
almalinux/9-minimal:9.2 image missing for linux/arm64v8 and linux/amd64

### ISSUE THREAD

**Issue by northerngit** [AlmaLinux/docker-images#108]
I appears that the UBI minimal image for 9.2 is missing from DockerHub

```
❯ docker pull --platform=linux/amd64 almalinux/9-minimal:9.2
9.2: Pulling from almalinux/9-minimal
no matching manifest for linux/amd64 in the manifest list entries
```
```
❯ docker pull --platform=linux/arm64 almalinux/9-minimal:9.2
9.2: Pulling from almalinux/9-minimal
no matching manifest for linux/arm64 in the manifest list entries
```

**Comment by LKHN** [comment]
:wave: 
Checking...

**Comment by LKHN** [comment]
Dear James, Thanks a lot for your contribution to help us for fixing the issue.

As I see the logs of the job, images were pushed as `almalinux/9-minimal:9.2-20230718` and `almalinux/9-minimal:9.2` without any error or warning. Strangely, while the first one has the four architectures, the second tag only had s390x.

As you can seen [here](https://hub.docker.com/r/almalinux/9-minimal/tags), both tags pointed to the same digests now.

**Comment by northerngit** [comment]
@LKHN Appreciate the update; the tags now parse correctly. Thank you for the quick resolution!
