### ISSUE TITLE
RPM DB junk in `almalinux/9-micro`

### ISSUE THREAD

**Issue by tangentsoft** [AlmaLinux/docker-images#114]
Simple repro case:

```
podman run -it --rm almalinux/9-micro sh
sh-5.1# ls /var/lib/rpm
rpmdb.sqlite  rpmdb.sqlite-shm  rpmdb.sqlite-wal
```

**Comment by pastalian** [comment]
I wouldn't call it _junk_ because it tells you what packages are installed in the image. But maybe people don't need it. I rarely use the micro image myself.

Anyway, this repo is outdated, and the current images are generated at https://github.com/AlmaLinux/container-images

**Comment by tangentsoft** [comment]
[Re-filed](https://github.com/AlmaLinux/container-images/issues/12).
