### ISSUE TITLE
Add systemd-enabled (ubi-minimal analog) image support

### ISSUE THREAD

**Issue by ezamriy** [AlmaLinux/docker-images#13]
EL8 offers 3 universal base images:

* `ubi-minimal` - a microdnf-based minimalistic image
* `ubi` - a default image with DNF and base utilities available (tar, find, vi, etc)
* `ubi-init` - a systemd-enabled image.

Currently, we are offering alternatives for the first two. It would be great if we can provide an `ubi-init` analog as well to have a full compatibility with upstream.

The #12 change can be used as an example.

**Comment by srbala** [comment]
I think we can add `ubi-micro` to the list

Personally `ubi-micro` + some utils like curl, tar would be most ideal for containers. that will os + app like dist only use.

**Comment by ezamriy** [comment]
Agree!

**Comment by srbala** [comment]
PR #14 will resolve this issue, anyone interested/help to `beta` test, please use my fork https://github.com/srbala/alma-docker-images/tree/fix-13
