### ISSUE TITLE
subscription-manager is not in default repo

### ISSUE THREAD

**Issue by hjimmy** [AlmaLinux/docker-images#2]
subscription-manager -xxxx.rpm is not in default repo,  which be defined in /etc/yum.repos.d/almalinux.repo. 
The url “http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/“ may contain this package.

**Comment by hjimmy** [comment]
# almalinux.repo
#
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for AlmaLinux updates
# unless you are manually picking other mirrors.
#
[baseos]
name=AlmaLinux 8.3 - BaseOS
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[appstream]
name=AlmaLinux 8.3 - AppStream
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/AppStream/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[powertools]
name=AlmaLinux 8.3 - PowerTools
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/PowerTools/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[extras]
name=AlmaLinux 8.3 - Extras
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/extras/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

## Sources
[baseos-source]
name=AlmaLinux 8.3 - BaseOS Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[appstream-source]
name=AlmaLinux 8.3 - AppStream Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/AppStream/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[powertools-source]
name=AlmaLinux 8.3 - PowerTools Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/PowerTools/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[extras-source]
name=AlmaLinux 8.3 - Extras Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/extras/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

## Debuginfo
[baseos-debuginfo]
name=AlmaLinux 8.3 - BaseOS debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[appstream-debuginfo]
name=AlmaLinux 8.3 - AppStream debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/AppStream/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[powertools-debuginfo]
name=AlmaLinux 8.3 - PowerTools debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/PowerTools/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[extras-debuginfo]
name=AlmaLinux 8.3 - Extras debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/extras/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

**Comment by ezamriy** [comment]
Thanks for reporting. The currently publicly available Docker image uses beta repositories without the subscription-manager package, yes. But the package is present in the RC repositories (see https://repo.almalinux.org/almalinux/8.3-rc/BaseOS/x86_64/os/Packages/subscription-manager-1.27.18-1.el8_3.alma.x86_64.rpm) so we just need to rebuild the image with an updated almalinux-release package.
I'm going to do this today/tomorrow.

**Comment by hjimmy** [comment]
` # almalinux.repo
#
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for AlmaLinux updates
# unless you are manually picking other mirrors.
#
[baseos]
name=AlmaLinux 8.3 - BaseOS
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[appstream]
name=AlmaLinux 8.3 - AppStream
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/AppStream/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[powertools]
name=AlmaLinux 8.3 - PowerTools
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/PowerTools/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[extras]
name=AlmaLinux 8.3 - Extras
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/extras/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

## Sources
[baseos-source]
name=AlmaLinux 8.3 - BaseOS Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[appstream-source]
name=AlmaLinux 8.3 - AppStream Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/AppStream/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[powertools-source]
name=AlmaLinux 8.3 - PowerTools Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/PowerTools/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[extras-source]
name=AlmaLinux 8.3 - Extras Source
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/extras/Source/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

## Debuginfo
[baseos-debuginfo]
name=AlmaLinux 8.3 - BaseOS debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[appstream-debuginfo]
name=AlmaLinux 8.3 - AppStream debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/AppStream/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[powertools-debuginfo]
name=AlmaLinux 8.3 - PowerTools debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/PowerTools/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux

[extras-debuginfo]
name=AlmaLinux 8.3 - Extras debuginfo
baseurl=https://repo.almalinux.org/almalinux/8.3-beta/extras/debug/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
`
Thanks , I found it in RC repo.

**Comment by ezamriy** [comment]
I've uploaded an updated Docker image based on RC to Docker Hub.
