### ISSUE TITLE
Use specific Dockerfile per image and architecture

### ISSUE THREAD

**Issue by LKHN** [AlmaLinux/docker-images#25]
The `init` and `micro` images need different Docker files than default and minimal. 
reference for init: 
* [2.4. Understanding the UBI init images](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index)
* [Running systemd in a non-privileged container Blog](https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container#)
I think it may give us the flexibility for image/architecture-specific metadata and other changes. 
Example: https://github.com/LKHN/docker-images/tree/buildsh-dockerfile

**Comment by srbala** [comment]
@LKHN doing some udpate to `build.sh`, we can manage without creating `Dockerfile`.  Script has `TYPE` has necessary to process it

OLD Generation step
```sh
cat << EOF > "${OUTPUT_DIR}/Dockerfile"
FROM scratch
ADD ${IMAGE_NAME} /
CMD ["/bin/bash"]
EOF
```
Proposed 
```sh
STARTCMD=$( cat <<EOF

CMD ["/bin/bash"]
EOF
)

if [ ${TYPE} == 'init' ]; then
  STARTCMD=$( cat <<EOF

CMD ["/bin/init"]

STOPSIGNAL SIGRTMIN+3
EOF
)
fi

if [ ${TYPE} == 'micro' ]; then
  STARTCMD=$( cat <<EOF

CMD ["/bin/sh"]
EOF
)
fi

cat << EOF > "${OUTPUT_DIR}/Dockerfile"
FROM scratch
ADD ${IMAGE_NAME} /
${STARTCMD}
EOF
```
