### ISSUE TITLE
Support for ppc64le images

### ISSUE THREAD

**Issue by smuzaffar** [AlmaLinux/docker-images#47]
Any news on ppc64le support ( https://github.com/AlmaLinux/docker-images/issues/4#issuecomment-861751092 ) ?

**Comment by LKHN** [comment]
Hey Malik! I'd say that's a great timing! Thank you! :pray: We're on the testing phase of the Generic Cloud image for the AlmaLinux OS 8.5 Beta 1 for ppc64le. We needs more eyes and testers. I just texted you in AlmaLinux chat If you interested to give it a shot to our testing images, let me know.

**Comment by srbala** [comment]
@smuzaffar `almalinux/8-base:8.5-beta-ppc64le` images are availale in dockerhub now, please give it a try

```sh
docker pull almalinux/8-base:8.5-beta-ppc64le
docker run --rm -it almalinux/8-base:8.5-beta-ppc64le
```

**Comment by srbala** [comment]
`minimal` images available at `almalinux/8-minimal:8.5-beta-ppc64le`

```sh
docker pull almalinux/8-minimal:8.5-beta-ppc64le
docker run --rm -it almalinux/8-minimal:8.5-beta-ppc64le
```

**Comment by smuzaffar** [comment]
thanks a lot @srbala . I am testing almalinux/8-base:8.5-beta-ppc64le now.

**Comment by srbala** [comment]
Since `ppc64le` is still in beta, let me check with the team.

**Comment by jaboutboul** [comment]
hey @smuzaffar and @srbala we are targeting to release STABLE in about two weeks.

**Comment by srbala** [comment]
@smuzaffar Official `ppe64le` arch images are available now.
