### ISSUE TITLE
Devel repo is missing

### ISSUE THREAD

**Issue by mtorromeo** [AlmaLinux/docker-images#5]
Hi, I am using the docker images to build rpm packages but the devel repo is missing from the mirrors and is making it impossible to build some rpms.

I need the libuv-devel package from that repo. This is the the corresponding centos mirror I am referring to:
http://centos.mirror.server24.net/8.3.2011/Devel/x86_64/os/Packages/

Thanks

**Comment by ezamriy** [comment]
Hi @mtorromeo, I believe it has been fixed in the AlmaLinux OS 8.4 release: http://repo.almalinux.org/almalinux/8/devel/.
