### ISSUE TITLE
almalinux/8-base:8.6 images not accessible on DockerHub for linux/arm64v8

### ISSUE THREAD

**Issue by northerngit** [AlmaLinux/docker-images#68]
There seems to be an issue with `linux/arm64v8` architecture for the `almalinux/8-base` image.

```
❯ docker pull almalinux/8-base:8.6
8.6: Pulling from almalinux/8-base
no matching manifest for linux/arm64/v8 in the manifest list entries
```

The artifacts appear to be on DockerHub, yet the image is not accessible.

**Comment by northerngit** [comment]
Thank you - The work around was sufficient to get our CI pipeline working!

**Comment by srbala** [comment]
@northerngit images updates have been posted, please verify

**Comment by northerngit** [comment]
@srbala Appreciate the update; the manifests now parse correctly.  Thank you!

**Comment by northerngit** [comment]
@srbala Appreciate the update; the manifests now parse correctly.  Thank you!
