### ISSUE TITLE
 almalinux/8-base:8.7 images on DockerHub missing linux/amd64 and linux/arm64 architectures

### ISSUE THREAD

**Issue by northerngit** [AlmaLinux/docker-images#85]
There seems to be an issue with `linux/amd64` and `linux/arm64` architectures for the almalinux/8-base image.

```
❯ docker pull almalinux/8-base:8.7 --platform=linux/amd64
8.7: Pulling from almalinux/8-base
no matching manifest for linux/amd64 in the manifest list entries
```

Digests only exist for `linux/ppc64le` and `linux/s390x`.

**Comment by LKHN** [comment]
Fixed. Thanks for the quick report!

**Comment by northerngit** [comment]
@LKHN Appreciate the update, thank you!
