### ISSUE TITLE
Create a minimal container

### ISSUE THREAD

**Issue by Bill-ColeUS** [AlmaLinux/docker-images#9]
Please consider creating a minimal container (tag), something similar to Fedora's minimal container.

https://registry.fedoraproject.org/repo/fedora-minimal/tags/

Thank you.

**Comment by ezamriy** [comment]
Since AlmaLinux OS is declared to be 1:1 RHEL compatible, I think we should have something very similar to RHEL [UBI images](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image).

**Comment by srbala** [comment]
AlmaLinux minimal similar to `ubi-minimal` would be nice, size of the image 50% small compare to regular image. Is PRs welcome? it can be derivied from regular image.

**Comment by ezamriy** [comment]
Hi @srbala, PRs are absolutely welcome!

Although it may be better to build a separate rootfs for minimal images. We can ask Docker official library maintainers how to do it properly.

In any case, please join our [chat](https://chat.almalinux.org/) where we have a special SIG/Cloud channel for such questions.
