### ISSUE TITLE
AlmaLinux 9.2 docker image 

### ISSUE THREAD

**Issue by kirill-zak** [AlmaLinux/docker-images#92]
Not docker image for AlmaLinux 9.2

**Comment by LKHN** [comment]
Since we got bunch of package updates from the upstream after the 9.2 release, decided to publish docker and cloud images to include all the updates. We are building them right now, so they will be published any minute now.

**Comment by kirill-zak** [comment]
AlmaLinux 9.2 docker image is available! Thank you!
