### ISSUE TITLE
Markdown-syntax-error at docker-pages for AlmaLinux 9

### ISSUE THREAD

**Issue by alexgit2k** [AlmaLinux/docker-images#95]
I think the left bracket is missing at `[latest, 9, 9.0](https://github.com/AlmaLinux/docker-images/tree/al-9.0.3-20220527` on:
- https://hub.docker.com/r/almalinux/9-base
- https://hub.docker.com/r/almalinux/9-minimal
- https://hub.docker.com/r/almalinux/9-init
- https://hub.docker.com/r/almalinux/9-micro

btw, why aren't these tags mentioned at https://hub.docker.com/_/almalinux?

**Comment by metalefty** [comment]
The syntax error has been fixed by @andrewlukoshko

**Comment by alexgit2k** [comment]
Thanks. Can confirm that it is correct now.
