### ISSUE TITLE
Images on quay.io are outdated

### ISSUE THREAD

**Issue by WebSpider** [AlmaLinux/docker-images#96]
It seems that images on quay.io are outdated, compared to dockerhub:

Quay: https://quay.io/repository/almalinux/almalinux?tab=tags (7 months old)
Dockerhub: https://hub.docker.com/_/almalinux/tags (2 months old)

Given that both are official distribution points as per https://wiki.almalinux.org/containers/docker-images.html, parity would be nice :)

**Comment by LKHN** [comment]
Hi and thanks for contribution.

Documentation was updated, please use https://quay.io/almalinuxorg , we push the same images at the same time here and Docker Hub.
